!@ File automatically generated by macro
!@(#) $Id$ - Version : 36.0.01000
@include $(KREDITNET_CONFIG_PATH)/basic.cfm
KreditNet.Config.Client.*.Trading.SourceShortName: KONDOR
KreditNet.*.*.Activated: False
KreditNet.*.*.LogToFile: True
