!@ File automatically generated by macro
!@(#) $Id$ - Version : 36.0.01000
@include $(KREDITNET_CONFIG_PATH)/DealManager.cfm
KreditNet.Config.PfeClient.*.ProtocolVersion: 2.6
KreditNet.Config.PfeClient.*.Request.PfeDeals: PFEDEALS.REQUEST
KreditNet.Config.PfeClient.*.SourceShortName: KONDOR
KreditNet.Config.PfeClient.*.Transport.Daemon: tcp:fusion-risk-rvd-svc:7500
KreditNet.Config.PfeClient.*.Transport.Network: localhost
KreditNet.Config.PfeClient.*.Transport.PingKillInterval: 9
KreditNet.Config.PfeClient.*.Transport.Service: 19039
KreditNet.Config.PfeClient.*.Transport.TimeOut: 10
