# Default values for rendezVous.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: registry.misys.global.ad
#  registry: registry-gdn.misys.global.ad
  repository: misys-common/tibco-rvd
  tag: 8.4.4
  pullPolicy: IfNotPresent