apiVersion: v1
kind: Service
metadata:
  name: {{ template "dataserver.name" . }}
  labels:
    app: {{ template "dataserver.name" . }}
    chart: {{ template "dataserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "dataserver.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dataserver.name" . }}-ext
  labels:
    app: {{ template "dataserver.name" . }}
    chart: {{ template "dataserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.extport }}
      protocol: TCP
  selector:
    app: {{ template "dataserver.name" . }}
    release: {{ .Release.Name }}