{{- if ne .Values.ingress.enabled true -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "treasury-ui.name" . }}-ext
  labels:
    app: {{ template "treasury-ui.name" . }}
    chart: {{ template "treasury-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.extport }}
      protocol: TCP
  selector:
    app: {{ template "treasury-ui.name" . }}
    release: {{ .Release.Name }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "treasury-ui.name" . }}
  labels:
    app: {{ template "treasury-ui.name" . }}
    chart: {{ template "treasury-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app: {{ template "treasury-ui.name" . }}
    release: {{ .Release.Name }}