dependencies:
  - name: rendezvous
    repository: http://localhost:8879/charts
    version: 0.1.0
    alias: fusion-risk-rvd

  - name: activeMQ
    repository: http://localhost:8879/charts
    version: 0.1.0
    alias: framq

  - name: frcargo
    repository: http://localhost:8879/charts
    version: 0.1.0

  - name: frcmr
    repository: http://localhost:8879/charts
    version: 0.1.0
