apiVersion: v1
kind: Service
metadata:
  name: {{ template "frcmr.name" . }}-ui
  labels:
    app: {{ template "frcmr.name" . }}
    chart: {{ template "frcmr.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.webport }}
      protocol: TCP
  selector:
    app: {{ template "frcmr.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "frcmr.fullname" . }}-ext
  labels:
    app: {{ template "frcmr.name" . }}
    chart: {{ template "frcmr.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.webport }}
      nodePort: {{ .Values.service.webNodePort }}
      protocol: TCP
  selector:
    app: {{ template "frcmr.name" . }}
    release: {{ .Release.Name }}
