# Default values for activeMQ.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  registry: registry.misys.global.ad
#  registry: registry-gdn.misys.global.ad
  repository: fusion-risk/activemq
  tag: 5.15.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 61616
