apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kondor
  labels:
    app: {{ template "kondor.name" . }}
    chart: {{ template "kondor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ $root := . }}
{{ range $path, $bytes := .Files.Glob "config/*" }}
{{ base $path | indent 2}}: |-
{{ ($root.Files.Get $path) | indent 4}}
{{ end }}